
# Netlify'da Next.js projesini dağıtmak için ayarlar
# https://docs.netlify.com/integrations/frameworks/next-js/

[build]
  # Next.js projesini derleme komutu
  command = "npm run build"
  
  # Derleme sonrası statik dosyaların bulunduğu klasör
  publish = ".next"

# Netlify'ın Next.js özelliklerini (SSR, Image Optimization vb.)
# doğru şekilde yönetmesini sağlayan eklenti.
[[plugins]]
  package = "@netlify/plugin-nextjs"

